#[unstable]
#build-std = ["std", "panic_abort"]

[build]
rustflags = [
    "-Ctarget-cpu=native",
    "-Clink-arg=-fuse-ld=lld",
    "-Cdebuginfo=0",
    "-Zthreads=24",
    "-Cforce-frame-pointers=no",
    "-Cprefer-dynamic=no",
    "-Cno-vectorize-loops",
    "-Cno-prepopulate-passes",
]
